env:
 - MARATHONVERSION: v1.10.19
 - MARATHONVERSION: v1.9.109
 - MARATHONVERSION: v1.6.322
 - MARATHONVERSION: v1.4.11
 - MARATHONVERSION: v1.3.0
 - MARATHONVERSION: v1.1.2

language: python
services:
  - docker
python:
  - 3.6
  - 3.7
before_install:
  - docker pull "missingcharacter/marathon-python:${MARATHONVERSION}"
  - docker run --name marathon-python -d -p 8080:8080 -p 5050:5050 "missingcharacter/marathon-python:${MARATHONVERSION}"
install:
  - pip install tox
script:
  - make test-py${TRAVIS_PYTHON_VERSION/./}
  - make itests-py${TRAVIS_PYTHON_VERSION/./}

# Work around travis-ci/travis-ci#5227
addons:
  hostname: localhost

os: linux
dist: xenial

deploy:
  - provider: pypi
    user: yelplabs
    password:
      secure: "Wl8GWxsfPy4KoORYH26N3FllvMeWrifzeCbEx2Af4corcBQl43heeiFRRTlUOcSX0TIasER21PUvQ0R0cAgCjfknDb3SOROcRtcSBe16+cMmvwysfxcAx2OcF1UYBPY8e/qOsGge2Zyzx2PAPNEmJoWKbIT3vUJ4WvlLVeGYdJ0="
    on:
      tags: true
      condition: $MARATHONVERSION == "v1.6.322"
      repo: thefactory/marathon-python
